/**
 * Generates tailored clash instances for each test and landmark in the prototype
 */

export function generateClashesForTest(testName = 'AR vs EL', iModel = 'Roberto Clemente Bridge') {
  const normTest = (testName || '').trim().toUpperCase();
  const normModel = (iModel || '').toLowerCase();

  // 1. Liberty Bridge Clashes
  if (normModel.includes('liberty')) {
    if (normTest.includes('ME VS FP')) {
      return [
        {
          id: 'CL-001',
          idNum: 'CL2F-00101',
          status: 'Suppressed',
          elementA: 'Hydronic_Deicing_Loop_L [Deck-Zone1]',
          elementB: 'FP_DryStandpipe_Header [Abutment-South]',
          modelA: 'Liberty_Deck_Hydronics.dgn',
          modelB: 'Liberty_FireProtection.dgn',
          categoryA: 'Mech_Hydronic_Deicing',
          penetration: '-0.38"',
          tags: ['Mechanical', 'Suppressed'],
        },
        {
          id: 'CL-002',
          idNum: 'CL2F-00102',
          status: '',
          elementA: 'Hydronic_Deicing_Loop_R [Deck-Zone1]',
          elementB: 'FP_DryStandpipe_Riser [Pier-2]',
          modelA: 'Liberty_Deck_Hydronics.dgn',
          modelB: 'Liberty_FireProtection.dgn',
          categoryA: 'Mech_Hydronic_Deicing',
          penetration: '-0.24"',
          tags: ['Mechanical'],
        },
        {
          id: 'CL-003',
          idNum: 'CL2F-00103',
          status: 'Suppressed',
          elementA: 'Hydronic_Supply_Manifold [Cantilever-Arm]',
          elementB: 'FP_Sprinkler_CrossMain [Deck-Flange]',
          modelA: 'Liberty_Deck_Hydronics.dgn',
          modelB: 'Liberty_FireProtection.dgn',
          categoryA: 'Mech_Hydronic_Deicing',
          penetration: '-0.52"',
          tags: ['Mechanical', 'Suppressed'],
        },
        {
          id: 'CL-004',
          idNum: 'CL2F-00104',
          status: 'Suppressed',
          elementA: 'Hydronic_Return_Header [Pier-1]',
          elementB: 'FP_Siamese_Connection_Feed [SouthHills]',
          modelA: 'Liberty_Deck_Hydronics.dgn',
          modelB: 'Liberty_FireProtection.dgn',
          categoryA: 'Mech_Hydronic_Deicing',
          penetration: '-0.18"',
          tags: ['Mechanical', 'Suppressed'],
        },
        {
          id: 'CL-005',
          idNum: 'CL2F-00105',
          status: '',
          elementA: 'Pump_Recirculation_Pipe [Abutment-North]',
          elementB: 'FP_BranchLine [Stringer-4]',
          modelA: 'Liberty_Deck_Hydronics.dgn',
          modelB: 'Liberty_FireProtection.dgn',
          categoryA: 'Mech_Hydronic_Deicing',
          penetration: '-0.31"',
          tags: ['Mechanical'],
        },
        {
          id: 'CL-006',
          idNum: 'CL2F-00106',
          status: 'Suppressed',
          elementA: 'Expansion_Joint_HeatTracer [Joint-03]',
          elementB: 'FP_Standpipe_Drain [RiverPier-West]',
          modelA: 'Liberty_Deck_Hydronics.dgn',
          modelB: 'Liberty_FireProtection.dgn',
          categoryA: 'Mech_Hydronic_Deicing',
          penetration: '-0.62"',
          tags: ['Mechanical', 'Suppressed'],
        },
        {
          id: 'CL-007',
          idNum: 'CL2F-00107',
          status: 'Suppressed',
          elementA: 'ChilledGlycol_Feeder [TunnelPortal]',
          elementB: 'FP_WetPipe_Sprinkler [PortalCanopy]',
          modelA: 'Liberty_Deck_Hydronics.dgn',
          modelB: 'Liberty_FireProtection.dgn',
          categoryA: 'Mech_Hydronic_Deicing',
          penetration: '-0.21"',
          tags: ['Plumbing', 'Suppressed'],
        },
        {
          id: 'CL-008',
          idNum: 'CL2F-00108',
          status: 'Suppressed',
          elementA: 'Deicing_Zone2_ValveBox [Pier-2]',
          elementB: 'FP_FlowSwitch_Assembly [FS-02]',
          modelA: 'Liberty_Deck_Hydronics.dgn',
          modelB: 'Liberty_FireProtection.dgn',
          categoryA: 'Mech_Hydronic_Deicing',
          penetration: '-0.45"',
          tags: ['Plumbing', 'Suppressed'],
        },
        {
          id: 'CL-009',
          idNum: 'CL2F-00109',
          status: '',
          elementA: 'Hydronic_Supply_Riser [FloorBeam-12]',
          elementB: 'FP_Main_Coupling [Grooved-6in]',
          modelA: 'Liberty_Deck_Hydronics.dgn',
          modelB: 'Liberty_FireProtection.dgn',
          categoryA: 'Mech_Hydronic_Deicing',
          penetration: '-0.36"',
          tags: ['Plumbing'],
        },
        {
          id: 'CL-010',
          idNum: 'CL2F-00110',
          status: '',
          elementA: 'Condensate_Drain [TunnelApproach]',
          elementB: 'FP_Hanger_Bracket [Trapeze-08]',
          modelA: 'Liberty_Deck_Hydronics.dgn',
          modelB: 'Liberty_FireProtection.dgn',
          categoryA: 'Mech_Hydronic_Deicing',
          penetration: '-0.14"',
          tags: ['Plumbing'],
        },
        {
          id: 'CL-011',
          idNum: 'CL2F-00111',
          status: '',
          elementA: 'Heat_Exchanger_Connection [Plenum]',
          elementB: 'FP_Test_InspectorConnection [North]',
          modelA: 'Liberty_Deck_Hydronics.dgn',
          modelB: 'Liberty_FireProtection.dgn',
          categoryA: 'Mech_Hydronic_Deicing',
          penetration: '-0.27"',
          tags: ['Plumbing'],
        },
        {
          id: 'CL-012',
          idNum: 'CL2F-00112',
          status: '',
          elementA: 'Secondary_Glycol_Return [Stringer-2]',
          elementB: 'FP_Seismic_Brace [GirderFlange]',
          modelA: 'Liberty_Deck_Hydronics.dgn',
          modelB: 'Liberty_FireProtection.dgn',
          categoryA: 'Mech_Hydronic_Deicing',
          penetration: '-0.53"',
          tags: ['Plumbing'],
        },
        {
          id: 'CL-013',
          idNum: 'CL2F-00113',
          status: '',
          elementA: 'Deicing_Sensor_Conduit [Lane-3]',
          elementB: 'FP_Auxiliary_Drain [LowPoint]',
          modelA: 'Liberty_Deck_Hydronics.dgn',
          modelB: 'Liberty_FireProtection.dgn',
          categoryA: 'Mech_Hydronic_Deicing',
          penetration: '-0.33"',
          tags: [],
        },
      ];
    }

    // Default for Liberty Bridge: AR vs ME (Tunnel Portal Architecture vs Tunnel Exhaust Plenums)
    return [
      {
        id: 'CL-001',
        idNum: 'CL2F-00071',
        status: 'Suppressed',
        elementA: 'Arch_TunnelPortal_Coping [SouthApproach]',
        elementB: 'Mech_Exhaust_PlenumDuct [Fan-01]',
        modelA: 'Liberty_Bridge_Arch.dgn',
        modelB: 'Liberty_Tunnel_Vent_Mech.dgn',
        categoryA: 'Tunnel_Portal_Architecture',
        penetration: '-0.42"',
        tags: ['Architectural', 'Suppressed'],
      },
      {
        id: 'CL-002',
        idNum: 'CL2F-00072',
        status: '',
        elementA: 'Arch_Parapet_FacadePanel [SouthHills]',
        elementB: 'Mech_AirIntake_Louver [Louv-02]',
        modelA: 'Liberty_Bridge_Arch.dgn',
        modelB: 'Liberty_Tunnel_Vent_Mech.dgn',
        categoryA: 'Tunnel_Portal_Architecture',
        penetration: '-0.28"',
        tags: ['Architectural'],
      },
      {
        id: 'CL-003',
        idNum: 'CL2F-00073',
        status: 'Suppressed',
        elementA: 'Arch_Soffit_CeilingGrid [TollPlaza]',
        elementB: 'Mech_SupplyAir_Duct_60x36 [MainTrunk]',
        modelA: 'Liberty_Bridge_Arch.dgn',
        modelB: 'Liberty_Tunnel_Vent_Mech.dgn',
        categoryA: 'Tunnel_Portal_Architecture',
        penetration: '-0.51"',
        tags: ['Architectural', 'Suppressed'],
      },
      {
        id: 'CL-004',
        idNum: 'CL2F-00074',
        status: 'Suppressed',
        elementA: 'Arch_Granite_ColumnWrap [SouthPier]',
        elementB: 'Mech_Exhaust_Silencer [Baffle-3]',
        modelA: 'Liberty_Bridge_Arch.dgn',
        modelB: 'Liberty_Tunnel_Vent_Mech.dgn',
        categoryA: 'Tunnel_Portal_Architecture',
        penetration: '-0.19"',
        tags: ['Architectural', 'Suppressed'],
      },
      {
        id: 'CL-005',
        idNum: 'CL2F-00075',
        status: '',
        elementA: 'Arch_Walkway_CanopyFrame [WestPed]',
        elementB: 'Mech_SmokeDamper_Frame [Damper-04]',
        modelA: 'Liberty_Bridge_Arch.dgn',
        modelB: 'Liberty_Tunnel_Vent_Mech.dgn',
        categoryA: 'Tunnel_Portal_Architecture',
        penetration: '-0.33"',
        tags: ['Architectural'],
      },
      {
        id: 'CL-006',
        idNum: 'CL2F-00076',
        status: 'Suppressed',
        elementA: 'Arch_Monumental_PylonFascia [NorthAbutment]',
        elementB: 'Mech_Exhaust_TransitionFitting [Trans-1A]',
        modelA: 'Liberty_Bridge_Arch.dgn',
        modelB: 'Liberty_Tunnel_Vent_Mech.dgn',
        categoryA: 'Tunnel_Portal_Architecture',
        penetration: '-0.65"',
        tags: ['Architectural', 'Suppressed'],
      },
      {
        id: 'CL-007',
        idNum: 'CL2F-00077',
        status: 'Suppressed',
        elementA: 'Mech_AirRelief_Hood [Deck-Level]',
        elementB: 'Plumb_StormHeader [FloorBeam-08]',
        modelA: 'Liberty_Bridge_Arch.dgn',
        modelB: 'Liberty_Tunnel_Vent_Mech.dgn',
        categoryA: 'Tunnel_Portal_Architecture',
        penetration: '-0.22"',
        tags: ['Plumbing', 'Suppressed'],
      },
      {
        id: 'CL-008',
        idNum: 'CL2F-00078',
        status: 'Suppressed',
        elementA: 'Mech_TunnelShaft_Damper [Exhaust-2]',
        elementB: 'Plumb_BridgeDrain_Catchbasin [CB-03]',
        modelA: 'Liberty_Bridge_Arch.dgn',
        modelB: 'Liberty_Tunnel_Vent_Mech.dgn',
        categoryA: 'Tunnel_Portal_Architecture',
        penetration: '-0.47"',
        tags: ['Plumbing', 'Suppressed'],
      },
      {
        id: 'CL-009',
        idNum: 'CL2F-00079',
        status: '',
        elementA: 'Mech_Vibration_IsolatorSpring [Base-4]',
        elementB: 'Plumb_Downspout_Pipe [RiverPier]',
        modelA: 'Liberty_Bridge_Arch.dgn',
        modelB: 'Liberty_Tunnel_Vent_Mech.dgn',
        categoryA: 'Tunnel_Portal_Architecture',
        penetration: '-0.38"',
        tags: ['Plumbing'],
      },
      {
        id: 'CL-010',
        idNum: 'CL2F-00080',
        status: '',
        elementA: 'Mech_Supply_DiffuserBox [PedestrianWalk]',
        elementB: 'Plumb_Cleanout_Fitting [CO-02]',
        modelA: 'Liberty_Bridge_Arch.dgn',
        modelB: 'Liberty_Tunnel_Vent_Mech.dgn',
        categoryA: 'Tunnel_Portal_Architecture',
        penetration: '-0.15"',
        tags: ['Plumbing'],
      },
      {
        id: 'CL-011',
        idNum: 'CL2F-00081',
        status: '',
        elementA: 'Mech_Duct_HangerTrapeze [TrussPanel-6]',
        elementB: 'Plumb_ExpansionLoop [Joint-North]',
        modelA: 'Liberty_Bridge_Arch.dgn',
        modelB: 'Liberty_Tunnel_Vent_Mech.dgn',
        categoryA: 'Tunnel_Portal_Architecture',
        penetration: '-0.29"',
        tags: ['Plumbing'],
      },
      {
        id: 'CL-012',
        idNum: 'CL2F-00082',
        status: '',
        elementA: 'Mech_Flex_Connector [FanIntake]',
        elementB: 'Plumb_DrainageTrough [Stringer-Bay]',
        modelA: 'Liberty_Bridge_Arch.dgn',
        modelB: 'Liberty_Tunnel_Vent_Mech.dgn',
        categoryA: 'Tunnel_Portal_Architecture',
        penetration: '-0.54"',
        tags: ['Plumbing'],
      },
      {
        id: 'CL-013',
        idNum: 'CL2F-00083',
        status: '',
        elementA: 'Arch_PortalSign_TrussMount [Sign-1]',
        elementB: 'Mech_Exhaust_StackCowl [RoofExit]',
        modelA: 'Liberty_Bridge_Arch.dgn',
        modelB: 'Liberty_Tunnel_Vent_Mech.dgn',
        categoryA: 'Tunnel_Portal_Architecture',
        penetration: '-0.35"',
        tags: [],
      },
    ];
  }

  // 2. PPG Place Clashes
  if (normModel.includes('ppg')) {
    return [
      {
        id: 'CL-001',
        idNum: 'CL2F-00061',
        status: 'Suppressed',
        elementA: 'Str_Gothic_CornerSpire_Frame [Tower-SW]',
        elementB: 'FP_Standpipe_Riser [HighRise-02]',
        modelA: 'PPG_Tower_Structural.dgn',
        modelB: 'PPG_FireProtection.dgn',
        categoryA: 'Gothic_Spire_Structural',
        penetration: '-0.42"',
        tags: ['Architectural', 'Suppressed'],
      },
      {
        id: 'CL-002',
        idNum: 'CL2F-00062',
        status: '',
        elementA: 'Str_CrownPyramid_DiagonalGirt [Level-42]',
        elementB: 'FP_SprinklerBranch_Pendant [Penthouse]',
        modelA: 'PPG_Tower_Structural.dgn',
        modelB: 'PPG_FireProtection.dgn',
        categoryA: 'Gothic_Spire_Structural',
        penetration: '-0.28"',
        tags: ['Architectural'],
      },
      {
        id: 'CL-003',
        idNum: 'CL2F-00063',
        status: 'Suppressed',
        elementA: 'Str_CurtainWall_OutriggerBeam [Level-44]',
        elementB: 'FP_Zoned_ControlValve_Assembly [ZCV-44]',
        modelA: 'PPG_Tower_Structural.dgn',
        modelB: 'PPG_FireProtection.dgn',
        categoryA: 'Gothic_Spire_Structural',
        penetration: '-0.51"',
        tags: ['Architectural', 'Suppressed'],
      },
      {
        id: 'CL-004',
        idNum: 'CL2F-00064',
        status: 'Suppressed',
        elementA: 'Str_SpirePinnacle_BaseRing [Pinnacle-Center]',
        elementB: 'FP_Standpipe_InspectorTest [TopRoof]',
        modelA: 'PPG_Tower_Structural.dgn',
        modelB: 'PPG_FireProtection.dgn',
        categoryA: 'Gothic_Spire_Structural',
        penetration: '-0.19"',
        tags: ['Architectural', 'Suppressed'],
      },
      {
        id: 'CL-005',
        idNum: 'CL2F-00065',
        status: '',
        elementA: 'Str_Wintergarden_SpaceFrameStrut [Node-14]',
        elementB: 'FP_Atrium_Deluge_Nozzle [Deluge-01]',
        modelA: 'PPG_Tower_Structural.dgn',
        modelB: 'PPG_FireProtection.dgn',
        categoryA: 'Gothic_Spire_Structural',
        penetration: '-0.33"',
        tags: ['Architectural'],
      },
      {
        id: 'CL-006',
        idNum: 'CL2F-00066',
        status: 'Suppressed',
        elementA: 'Str_Column_C6_FlangeStiffener [Level-40]',
        elementB: 'FP_Sprinkler_CrossMain_6in [Corridor]',
        modelA: 'PPG_Tower_Structural.dgn',
        modelB: 'PPG_FireProtection.dgn',
        categoryA: 'Gothic_Spire_Structural',
        penetration: '-0.65"',
        tags: ['Architectural', 'Suppressed'],
      },
      {
        id: 'CL-007',
        idNum: 'CL2F-00067',
        status: 'Suppressed',
        elementA: 'Str_PlazaBuilding_RoofBeam [TwoPPG-Roof]',
        elementB: 'FP_DryPipe_ValveHeader [Plaza-Vault]',
        modelA: 'PPG_Tower_Structural.dgn',
        modelB: 'PPG_FireProtection.dgn',
        categoryA: 'Gothic_Spire_Structural',
        penetration: '-0.22"',
        tags: ['Plumbing', 'Suppressed'],
      },
      {
        id: 'CL-008',
        idNum: 'CL2F-00068',
        status: 'Suppressed',
        elementA: 'Str_ElevatorCore_HeaderBeam [Elev-BankA]',
        elementB: 'FP_FireHose_Cabinet_Feed [Floor-42]',
        modelA: 'PPG_Tower_Structural.dgn',
        modelB: 'PPG_FireProtection.dgn',
        categoryA: 'Gothic_Spire_Structural',
        penetration: '-0.47"',
        tags: ['Plumbing', 'Suppressed'],
      },
      {
        id: 'CL-009',
        idNum: 'CL2F-00069',
        status: '',
        elementA: 'Str_Cantilever_FloorOutrigger [NorthFace]',
        elementB: 'FP_Flexible_SprinklerDrop [Head-42A]',
        modelA: 'PPG_Tower_Structural.dgn',
        modelB: 'PPG_FireProtection.dgn',
        categoryA: 'Gothic_Spire_Structural',
        penetration: '-0.38"',
        tags: ['Plumbing'],
      },
      {
        id: 'CL-010',
        idNum: 'CL2F-00070',
        status: '',
        elementA: 'Str_Spire_TieRod_Brace [Spire-NE]',
        elementB: 'FP_FlowSwitch_Tee [Riser-2]',
        modelA: 'PPG_Tower_Structural.dgn',
        modelB: 'PPG_FireProtection.dgn',
        categoryA: 'Gothic_Spire_Structural',
        penetration: '-0.15"',
        tags: ['Plumbing'],
      },
      {
        id: 'CL-011',
        idNum: 'CL2F-00071',
        status: '',
        elementA: 'Str_Spandrel_Beam_W24 [Level-41]',
        elementB: 'FP_Main_Coupling [Rigid-4in]',
        modelA: 'PPG_Tower_Structural.dgn',
        modelB: 'PPG_FireProtection.dgn',
        categoryA: 'Gothic_Spire_Structural',
        penetration: '-0.29"',
        tags: ['Plumbing'],
      },
      {
        id: 'CL-012',
        idNum: 'CL2F-00072',
        status: '',
        elementA: 'Str_GlassPurlin_SupportClip [Wintergarden]',
        elementB: 'FP_DrainLine_2in [BasementDischarge]',
        modelA: 'PPG_Tower_Structural.dgn',
        modelB: 'PPG_FireProtection.dgn',
        categoryA: 'Gothic_Spire_Structural',
        penetration: '-0.54"',
        tags: ['Plumbing'],
      },
      {
        id: 'CL-013',
        idNum: 'CL2F-00073',
        status: '',
        elementA: 'Str_Helipad_SupportStub [SpireCrown]',
        elementB: 'FP_FoamSuppression_Nozzle [TopPlatform]',
        modelA: 'PPG_Tower_Structural.dgn',
        modelB: 'PPG_FireProtection.dgn',
        categoryA: 'Gothic_Spire_Structural',
        penetration: '-0.35"',
        tags: [],
      },
    ];
  }

  // 3. Default: Roberto Clemente Bridge Clashes
  return [
    {
      id: 'CL-001',
      idNum: 'CL2F-00001',
      status: 'Suppressed',
      elementA: 'TC_Asph Conc Base Cse Shld_L [3-8PO]',
      elementB: 'Node: SA1-81 [3-2K0]',
      modelA: 'Roberto_Clemente_Arch.dgn',
      modelB: 'Roberto_Clemente_Elect.dgn',
      categoryA: 'Promenade_Architectural',
      penetration: '-0.42"',
      tags: ['Architectural', 'Suppressed'],
    },
    {
      id: 'CL-002',
      idNum: 'CL2F-00002',
      status: '',
      elementA: 'TC_Asph Conc Base Cse Shld_L [3-8PO]',
      elementB: 'Node: SA1-82 [3-2K0]',
      modelA: 'Roberto_Clemente_Arch.dgn',
      modelB: 'Roberto_Clemente_Elect.dgn',
      categoryA: 'Promenade_Architectural',
      penetration: '-0.28"',
      tags: ['Architectural'],
    },
    {
      id: 'CL-003',
      idNum: 'CL2F-00003',
      status: 'Suppressed',
      elementA: 'TC_Asph Conc Base Cse Shld_L [3-8PO]',
      elementB: 'Node: SA1-83 [3-2K0]',
      modelA: 'Roberto_Clemente_Arch.dgn',
      modelB: 'Roberto_Clemente_Elect.dgn',
      categoryA: 'Promenade_Architectural',
      penetration: '-0.51"',
      tags: ['Architectural', 'Suppressed'],
    },
    {
      id: 'CL-004',
      idNum: 'CL2F-00004',
      status: 'Suppressed',
      elementA: 'TC_Asph Conc Base Cse Shld_L [3-8PO]',
      elementB: 'Node: SA1-84 [3-2K0]',
      modelA: 'Roberto_Clemente_Arch.dgn',
      modelB: 'Roberto_Clemente_Elect.dgn',
      categoryA: 'Promenade_Architectural',
      penetration: '-0.19"',
      tags: ['Architectural', 'Suppressed'],
    },
    {
      id: 'CL-005',
      idNum: 'CL2F-00005',
      status: '',
      elementA: 'TC_Asph Conc Base Cse Shld_L [3-8PO]',
      elementB: 'Node: SA1-85 [3-2K0]',
      modelA: 'Roberto_Clemente_Arch.dgn',
      modelB: 'Roberto_Clemente_Elect.dgn',
      categoryA: 'Promenade_Architectural',
      penetration: '-0.33"',
      tags: ['Architectural'],
    },
    {
      id: 'CL-006',
      idNum: 'CL2F-00006',
      status: 'Suppressed',
      elementA: 'TC_Asph Conc Base Cse Shld_L [3-8PO]',
      elementB: 'Node: SA1-86 [3-2K0]',
      modelA: 'Roberto_Clemente_Arch.dgn',
      modelB: 'Roberto_Clemente_Elect.dgn',
      categoryA: 'Promenade_Architectural',
      penetration: '-0.65"',
      tags: ['Architectural', 'Suppressed'],
    },
    {
      id: 'CL-007',
      idNum: 'CL2F-00007',
      status: 'Suppressed',
      elementA: 'TC_Asph Conc Base Cse Shld_L [3-8PO]',
      elementB: 'Node: SA1-87 [3-2K0]',
      modelA: 'Roberto_Clemente_Arch.dgn',
      modelB: 'Roberto_Clemente_Elect.dgn',
      categoryA: 'Promenade_Architectural',
      penetration: '-0.22"',
      tags: ['Plumbing', 'Suppressed'],
    },
    {
      id: 'CL-008',
      idNum: 'CL2F-00008',
      status: 'Suppressed',
      elementA: 'TC_Asph Conc Base Cse Shld_L [3-8PO]',
      elementB: 'Node: SA1-88 [3-2K0]',
      modelA: 'Roberto_Clemente_Arch.dgn',
      modelB: 'Roberto_Clemente_Elect.dgn',
      categoryA: 'Promenade_Architectural',
      penetration: '-0.47"',
      tags: ['Plumbing', 'Suppressed'],
    },
    {
      id: 'CL-009',
      idNum: 'CL2F-00009',
      status: '',
      elementA: 'TC_Asph Conc Base Cse Shld_L [3-8PO]',
      elementB: 'Node: SA1-89 [3-2K0]',
      modelA: 'Roberto_Clemente_Arch.dgn',
      modelB: 'Roberto_Clemente_Elect.dgn',
      categoryA: 'Promenade_Architectural',
      penetration: '-0.38"',
      tags: ['Plumbing'],
    },
    {
      id: 'CL-010',
      idNum: 'CL2F-00010',
      status: '',
      elementA: 'TC_Asph Conc Base Cse Shld_L [3-8PO]',
      elementB: 'Node: SA1-90 [3-2K0]',
      modelA: 'Roberto_Clemente_Arch.dgn',
      modelB: 'Roberto_Clemente_Elect.dgn',
      categoryA: 'Promenade_Architectural',
      penetration: '-0.15"',
      tags: ['Plumbing'],
    },
    {
      id: 'CL-011',
      idNum: 'CL2F-00011',
      status: '',
      elementA: 'TC_Asph Conc Base Cse Shld_L [3-8PO]',
      elementB: 'Node: SA1-91 [3-2K0]',
      modelA: 'Roberto_Clemente_Arch.dgn',
      modelB: 'Roberto_Clemente_Elect.dgn',
      categoryA: 'Promenade_Architectural',
      penetration: '-0.29"',
      tags: ['Plumbing'],
    },
    {
      id: 'CL-012',
      idNum: 'CL2F-00012',
      status: '',
      elementA: 'TC_Asph Conc Base Cse Shld_L [3-8PO]',
      elementB: 'Node: SA1-92 [3-2K0]',
      modelA: 'Roberto_Clemente_Arch.dgn',
      modelB: 'Roberto_Clemente_Elect.dgn',
      categoryA: 'Promenade_Architectural',
      penetration: '-0.54"',
      tags: ['Plumbing'],
    },
    {
      id: 'CL-013',
      idNum: 'CL2F-00013',
      status: '',
      elementA: 'TC_Asph Conc Base Cse Shld_L [3-8PO]',
      elementB: 'Node: SA1-81 [3-2K0]',
      modelA: 'Roberto_Clemente_Arch.dgn',
      modelB: 'Roberto_Clemente_Elect.dgn',
      categoryA: 'Promenade_Architectural',
      penetration: '-0.35"',
      tags: [],
    },
  ];
}
